# Generated by Django 4.1.2 on 2022-12-01 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='like',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
